### ISSUE TITLE
Configure script stops at "Sorry, this Syndicate Wars port will only run on i386 processors"

### ISSUE THREAD

**Issue by Dartomic** [mefistotelis/swars#6]
configure: error: Sorry, this Syndicate Wars port will only run on i386 processors

The i386 dependencies are installed on Ubuntu 22.04

**Comment by mefistotelis** [comment]
This means that trial compilation of simple 32-bit code failed. Did you set "-m32" flags, as the README suggests?

**Comment by Dartomic** [comment]
I realized I messed up, so I copied all the instructions to a script to run before coming back here, just in case it's still an issue.

Sorry about that, it's not showing as an issue anymore.

But now I am having assembler errors. I know it's a separate issue, unless I messed up again. But I don't know what to label the issue as, if it is one. So I'll just post the output here:

make[2]: Entering directory '/home/hsmith/Downloads/swars-0.3.1.16/release/src'
gcc  -m32 -c -o ariadne.o ../../src/ariadne.s
../../src/ariadne.s: Assembler messages:
../../src/ariadne.s:10: Error: junk at end of line, first unrecognized character is `\'
../../src/ariadne.s:11: Error: no such instruction: `sym '
../../src/ariadne.s:14: Error: no such instruction: `global (sym)'
../../src/ariadne.s:19: Error: junk at end of line, first unrecognized character is `('
../../src/ariadne.s:19: Error: junk at end of line, first unrecognized character is `\'
../../src/ariadne.s:20: Error: no such instruction: `export_symbol (sym)'
../../src/ariadne.s:21: Error: no such instruction: `sym '
../../src/ariadne.s:24: Error: junk at end of line, first unrecognized character is `\'
../../src/ariadne.s:25: Error: no such instruction: `global (sym)'
make[2]: *** [Makefile:511: ariadne.o] Error 1
make[2]: Leaving directory '/home/hsmith/Downloads/swars-0.3.1.16/release/src'
make[1]: *** [Makefile:366: all] Error 2
make[1]: Leaving directory '/home/hsmith/Downloads/swars-0.3.1.16/release/src'
make: *** [Makefile:417: all-recursive] Error 1

**Comment by mefistotelis** [comment]
I am confused, currently the repo contains `ariadne.sx` and not `ariadne.s`. I renamed the files because the extension should be upper case (`.S`) and that is hard to manage on Windows where case doesn't matter to the OS.

Are you building an old source?

**Comment by Dartomic** [comment]
I downloaded 0.3.1.16 from the release page.

**Comment by mefistotelis** [comment]
Maybe go with latest git code - this way the issues you face will help improve the project.

That release has no `.s` vs `.S` distinction - you'd have to know which files require parser, and rename the extensions to upper case.

**Comment by Dartomic** [comment]
That fixed the assembler errors I think.

Now I am getting compilation errors:

[err.txt](https://github.com/mefistotelis/swars/files/8622141/err.txt)

**Comment by mefistotelis** [comment]
For `time_t` you can include the proper header.

For `dir.h` - that contains Windows version of old DOS findfirst/findnext API.
Syndicate Wars uses it for minor things, like figuring out unused name for a screenshot.
I guess I should simulate that API in a future version, to make other Bullfrog games work with this library.
To get pass that now, you'd have to use one of existing implementations of findfirst/findnext for Linux.
You will find such projects on github.

**Comment by Dartomic** [comment]
It compiles after you updated some of the code, and updated the dependencies list. 

There is another dependency, at least there was before you updated things:
sudo apt install build-essential libtool

autoreconf was failing to execute libtoolize without those.

The make file in the utils directory doesn't install the game though. The installation program hasn't exited yet, but it's not doing anything in my CPU either. I think it's waiting for something, but I'm not sure.

My game files all have capital letters, and I noticed that the source code uses lower case for the config.ini file name. I moved all of the files into the "usr/local/share/swars" directory, and the executable swars file couldn't use the config.ini file until I renamed it. Do they all need to be lower case?

**Comment by Dartomic** [comment]
Also, I found a replacement for findfirst/findnext. I was editing the source code to test it out, but the edits you made allowed the code to compile, so I stopped. 

Just incase this makes some things easier, here you go:
https://github.com/MathieuTurcotte/findfirst

**Comment by Dartomic** [comment]
I renamed all files to lower case, and the game appears to launch and exit really fast, setting my display to something like 640x480

**Comment by mefistotelis** [comment]
Use GDB to trace the crash. And run in a window to avoid res change.
(btw you can restart Gnome with alt+F2 then "r", if that's what you use)

Example:
```
gdb -ex "run" --args swars -m 71 -H -W
```

I just fixed one of such crashes here:
https://github.com/mefistotelis/swars/commit/0db03f3d2d467861da7a42aae2dde93ecb3a21e1

**Comment by mefistotelis** [comment]
That's funny, `alltext` is expected in lower case, but its extensions are in upper. I guess everything should be normalized to just use lower case.

**Comment by Dartomic** [comment]
> you can restart Gnome with alt+F2 then "r", if that's what you use

I mate, that brings up a program like windows "run program" 

> I just fixed one of such crashes here: [0db03f3](https://github.com/mefistotelis/swars/commit/0db03f3d2d467861da7a42aae2dde93ecb3a21e1)

So this might be the same crash that you're talking about, but just in case, I'll post the output of GDB here for you.

[gdb.txt](https://github.com/mefistotelis/swars/files/8633162/gdb.txt)

**Comment by Dartomic** [comment]
> That's funny, `alltext` is expected in lower case, but its extensions are in upper. I guess everything should be normalized to just use lower case.

Why is that in assembly? It's cool, but it's pretty much an array, right?

**Comment by Dartomic** [comment]
I just ran the latest source code from the repo here and gdb is still showing the same output.

**Comment by mefistotelis** [comment]
You must have some issues with files. Make sure everything is lower case.
Especially sprites.
For me, the latest repo works on Ubuntu (though I tested it before last commit, so many texts were missing).

**Comment by Dartomic** [comment]
I may have put some things in the wrong place, or forgot to move something

[tree.txt](https://github.com/mefistotelis/swars/files/8633344/tree.txt)

**Comment by Dartomic** [comment]
My config.ini dos paths. That's not right, is it?

[config.txt](https://github.com/mefistotelis/swars/files/8633422/config.txt)

I changed the extension to txt so that I can post it here.

**Comment by Dartomic** [comment]
I just ran the Windows version of this in wine on my files. My game works in DOSBOX, but I think something is corrupted in my files, because it has an error either right after, or during, converting track_3.wav to track_3.ogg.

So I'm pretty sure you fixed what ever problems people might reasonably have on Ubuntu.

**Comment by mefistotelis** [comment]
Thanks for the motivation to make it work again.

**Comment by Dartomic** [comment]
Does this work with digital files from distributions of the game provided by GOG or EA, if the installer is bypassed, and I convert the wav files myself? I could purchase a CD of the game from ebay, but I would rather support the distribution of new purchases of the game.

**Comment by Dartomic** [comment]
I extracted my copy from the archive dot org web emulator, because it didn't run well in the web browser.
